version: '3.8'

services:
  c2_server:
    container_name: c2_server
    image: python:3.9-slim
    command: python3 -m http.server 8080
    networks:
      - micro_internet

  dns:
    container_name: dns
    image: busybox
    command: sleep infinity
    networks:
      - micro_internet

  webserver:
    container_name: webserver
    image: python:3.9-slim
    command: python3 -m http.server 80
    networks:
      - micro_internet

  fileshare:
    container_name: fileshare
    image: busybox
    command: sleep infinity
    volumes:
      - ./shared_data:/data
    networks:
      - micro_internet

  victim:
    container_name: victim
    image: python:3.9-slim
    command: python3 -m http.server 8888
    networks:
      - micro_internet

  malware:
    build: .
    container_name: malware
    command: python3 worm.py c2_server dns webserver fileshare victim
    volumes:
      - ./shared_data:/data
    networks:
      - micro_internet
    depends_on:
      - c2_server
      - dns
      - webserver
      - fileshare
      - victim

networks:
  micro_internet:
    driver: bridge
    internal: true