version: '3.8'

services:
  # --- FLASK  ---
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    user: "root" 
    volumes:
      - ./flask/templates:/app/templates
      - ./flask/static:/app/static
      - ./shared_data:/uploads
    ports:
      - "8000:8000"
    networks:
      - micro_internet

  # --- VULNERABLE SERVICES ---
  webserver:
    container_name: webserver
    image: python:3.9-slim
    volumes:
      - ./python/vulnerable_server.py:/vulnerable_server.py
    command: python3 -u /vulnerable_server.py
    networks:
      - micro_internet

  victim:
    container_name: victim
    image: python:3.9-slim
    command: python3 -u -m http.server 8888
    networks:
      - micro_internet

  # --- INFRASTRUCTURE ---
  dns:
    container_name: dns
    image: busybox
    command: sleep infinity
    networks:
      - micro_internet

  fileshare:
    container_name: fileshare
    image: busybox
    command: sleep infinity
    volumes:
      - ./shared_data:/data
    networks:
      - micro_internet

  # --- IDS/IPS (Imported Snort) ---
  # ids:
  #   container_name: ids
  #   image: jasonish/snort
  #   volumes:
  #     - ./ids/rules:/etc/snort/rules
  #     - ./ids/logs:/var/log/snort
  #   # Running snort with custom local rules
  #   command: -i eth0 -c /etc/snort/rules/local.rules -A console
  #   networks:
  #     - micro_internet

  # ips:
  #   container_name: ips
  #   image: alpine
  #   volumes:
  #     - ./ids/logs:/logs:ro
  #     - ./ips/blocklist:/blocklist
  #   command: /bin/sh -c "tail -f /logs/snort.alert"
  #   networks:
  #     - micro_internet
  #   depends_on:
  #     - ids

  honeypot:
    container_name: honeypot
    image: python:3.9-slim
    command: python3 -u -m http.server 2222
    networks:
      - micro_internet

networks:
  micro_internet:
    driver: bridge
    internal: true